syntax = "proto3";

package auth.v1;

service AuthService {
    rpc SendOTP(SendOTPRequest) returns (SendOTPResponse);
    rpc VerifyOTP(VerifyOTPRequest) returns (VerifyOTPResponse);
    rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
}

message SendOTPRequest {
    string identifier = 1;
    string type = 2;
}


message SendOTPResponse {
    bool ok = 1;
}

message VerifyOTPRequest {
    string identifier = 1;
    string type = 2;
    string code = 3;
}

message VerifyOTPResponse {
    string access_token = 1;
    string refresh_token = 2;
}

message RefreshTokenRequest {
    string refresh_token = 1;
}

message RefreshTokenResponse {
    string access_token = 1;
    string refresh_token = 2;
}